# Generated by Django 4.2.30 on 2026-04-07 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.URLField(max_length=500)),
                ('scan_type', models.CharField(choices=[('basic', 'Basic Scan'), ('full', 'Full Scan'), ('quick', 'Quick Scan')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('results', models.JSONField(blank=True, null=True)),
                ('vulnerabilities_found', models.IntegerField(default=0)),
                ('scan_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('scan_completed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scan_started'],
            },
        ),
    ]
