<?php
// 1. ENABLE ERROR REPORTING
error_reporting(E_ALL);
ini_set('display_errors', 0);

require_once 'db_connect.php';
require_once 'fpdf.php';

// 2. GET SCAN ID
if (!isset($_GET['id'])) {
    die("Error: No Scan ID provided.");
}
$scan_id = intval($_GET['id']);

// 3. FETCH DATA FROM DB
$sql = "SELECT * FROM django_scans WHERE id = ?"; 
$stmt = $conn->prepare($sql);
$stmt->bind_param("i", $scan_id);
$stmt->execute();
$result = $stmt->get_result();
$scan = $result->fetch_assoc();

if (!$scan) {
    die("Error: Scan not found.");
}

$target = $scan['target_url'];
$date = $scan['created_at'];
$json_data = json_decode($scan['result_data'], true);

// 4. EXTRACT DATA SAFELY
$summary = isset($json_data['summary']) ? $json_data['summary'] : [];
$full_res = isset($json_data['full_scan_results']) ? $json_data['full_scan_results'] : [];

// --- FIX: RENAMED CLASS TO 'ScanReportPDF' TO AVOID CONFLICTS ---
class ScanReportPDF extends FPDF {
    function Header() {
        // Logo
        if(file_exists('../assets/images/logo.png')) {
            $this->Image('../assets/images/logo.png', 10, 6, 30);
        }
        // Font
        $this->SetFont('Arial', 'B', 15);
        // Title
        $this->Cell(80);
        $this->Cell(30, 10, 'Vulnerability Scan Report', 0, 0, 'C');
        // Line break
        $this->Ln(20);
        
        // Decorator Line
        $this->SetDrawColor(50, 50, 50);
        $this->Line(10, 25, 200, 25);
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->SetTextColor(128);
        $this->Cell(0, 10, 'Page ' . $this->PageNo() . ' - Confidential Security Report - Generated by AVS', 0, 0, 'C');
    }

    function ChapterTitle($label) {
        $this->SetFont('Arial', 'B', 14);
        $this->SetFillColor(230, 230, 230);
        $this->Cell(0, 10, "  $label", 0, 1, 'L', true);
        $this->Ln(4);
    }

    function SectionHeader($label) {
        $this->SetFont('Arial', 'B', 12);
        $this->SetTextColor(0, 51, 102);
        $this->Cell(0, 10, $label, 0, 1, 'L');
        $this->SetTextColor(0); 
    }
    
    function InfoRow($label, $value) {
        $this->SetFont('Arial', 'B', 10);
        $this->Cell(50, 8, $label, 0, 0);
        $this->SetFont('Arial', '', 10);
        $this->Cell(0, 8, $value, 0, 1);
    }
}

// 5. START PDF GENERATION (Using the new unique class name)
$pdf = new ScanReportPDF();
$pdf->AddPage();
$pdf->SetFont('Arial', '', 12);

// --- TITLE PAGE ---
$pdf->SetFont('Arial', 'B', 24);
$pdf->Cell(0, 20, 'Security Assessment Report', 0, 1, 'C');
$pdf->Ln(10);

$pdf->SetFont('Arial', '', 12);
$pdf->InfoRow("Target Host:", $target);
$pdf->InfoRow("Scan Date:", $date);
$pdf->InfoRow("Scan Type:", "Full Infrastructure & Web Audit");
$pdf->InfoRow("Generated By:", "Automated Vulnerability Scanner (AVS)");

// RISK BADGE
$risk_score = isset($summary['risk_score']) ? $summary['risk_score'] : 0;
$risk_level = isset($summary['risk_level']) ? $summary['risk_level'] : "Unknown";

$pdf->Ln(10);
$pdf->SetFont('Arial', 'B', 14);
$pdf->Cell(40, 10, "Risk Level:", 0, 0);

if ($risk_score > 50) {
    $pdf->SetTextColor(200, 0, 0); // Red
} elseif ($risk_score > 20) {
    $pdf->SetTextColor(255, 165, 0); // Orange
} else {
    $pdf->SetTextColor(0, 128, 0); // Green
}
$pdf->Cell(0, 10, strtoupper($risk_level) . " (Score: $risk_score)", 0, 1);
$pdf->SetTextColor(0); // Reset
$pdf->Ln(10);

// --- EXECUTIVE SUMMARY ---
$pdf->ChapterTitle("1. Executive Summary");
$pdf->MultiCell(0, 8, "This report contains the results of a comprehensive security scan. The automated system performed Network discovery (Nmap), Database testing (SQLMap), Server configuration analysis (Nikto), and Client-side attack simulation (XSS).");
$pdf->Ln(5);

// Summary Table
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(60, 10, 'Scan Module', 1);
$pdf->Cell(40, 10, 'Status', 1);
$pdf->Cell(90, 10, 'Primary Finding', 1);
$pdf->Ln();

$pdf->SetFont('Arial', '', 10);

// Helper to extract status safely
$nmap_stat = isset($full_res['nmap']['status']) ? $full_res['nmap']['status'] : 'N/A';
$sqli_stat = isset($full_res['SQLi']['status']) ? $full_res['SQLi']['status'] : 'N/A';
$xss_stat = isset($full_res['XSS']['status']) ? $full_res['XSS']['status'] : 'N/A';
$nikto_stat = isset($full_res['nikto']['status']) ? $full_res['nikto']['status'] : 'N/A';

// Helper to count Nmap ports
$nmap_ports = isset($full_res['nmap']['open_ports']) ? count($full_res['nmap']['open_ports']) : 0;
// Helper to check Vulns
$sqli_vuln = (isset($full_res['SQLi']['status']) && $full_res['SQLi']['status'] == 'Vulnerable') ? "Critical SQLi Found" : "Safe";
$xss_vuln = (isset($full_res['XSS']['status']) && $full_res['XSS']['status'] == 'Vulnerable') ? "XSS Found" : "Safe";

$pdf->Cell(60, 8, 'Network Scan (Nmap)', 1);
$pdf->Cell(40, 8, $nmap_stat, 1);
$pdf->Cell(90, 8, "$nmap_ports Open Ports Detected", 1);
$pdf->Ln();

$pdf->Cell(60, 8, 'Database Security (SQLMap)', 1);
$pdf->Cell(40, 8, $sqli_stat, 1);
$pdf->Cell(90, 8, $sqli_vuln, 1);
$pdf->Ln();

$pdf->Cell(60, 8, 'Web Security (XSS)', 1);
$pdf->Cell(40, 8, $xss_stat, 1);
$pdf->Cell(90, 8, $xss_vuln, 1);
$pdf->Ln();

$pdf->Cell(60, 8, 'Server Config (Nikto)', 1);
$pdf->Cell(40, 8, $nikto_stat, 1);
$pdf->Cell(90, 8, "Configuration Analyzed", 1);
$pdf->Ln(10);

// --- DETAILED FINDINGS ---
$pdf->AddPage();
$pdf->ChapterTitle("2. Detailed Technical Findings");

// 2.1 NMAP
$pdf->SectionHeader("2.1 Network Infrastructure (Nmap)");
if(isset($full_res['nmap']['open_ports']) && !empty($full_res['nmap']['open_ports'])) {
    $pdf->SetFont('Arial', 'B', 9);
    $pdf->Cell(30, 8, 'Port', 1);
    $pdf->Cell(50, 8, 'Service', 1);
    $pdf->Cell(40, 8, 'Risk', 1);
    $pdf->Ln();
    $pdf->SetFont('Arial', '', 9);
    
    foreach ($full_res['nmap']['open_ports'] as $port) {
        if (is_array($port)) {
             $p_id = $port['port'] ?? 'Unknown';
             $p_svc = $port['service'] ?? 'Unknown';
             $p_risk = $port['risk'] ?? 'Low';
        } else {
             $p_id = $port;
             $p_svc = "Detailed info in raw log";
             $p_risk = "Medium";
        }
        $pdf->Cell(30, 8, $p_id, 1);
        $pdf->Cell(50, 8, substr($p_svc, 0, 25), 1);
        $pdf->Cell(40, 8, $p_risk, 1);
        $pdf->Ln();
    }
} else {
    $pdf->Cell(0, 10, "No open ports found or Nmap failed.", 0, 1);
}
$pdf->Ln(5);

// 2.2 SQLi
$pdf->SectionHeader("2.2 Database Vulnerabilities (SQLMap)");
if(isset($full_res['SQLi']['findings']) && !empty($full_res['SQLi']['findings'])) {
    $pdf->SetTextColor(200,0,0);
    $pdf->Cell(0, 10, "CRITICAL: SQL Injection Vectors Discovered", 0, 1);
    $pdf->SetTextColor(0);
    $pdf->SetFont('Arial', '', 9);
    foreach($full_res['SQLi']['findings'] as $find) {
        $type = isset($find['type']) ? $find['type'] : "Unknown SQLi";
        $sev = isset($find['severity']) ? $find['severity'] : "Critical";
        $pdf->MultiCell(0, 6, "- $type ($sev)", 0, 'L');
    }
} else {
    $pdf->Cell(0, 10, "No SQL Injection vulnerabilities detected.", 0, 1);
}
$pdf->Ln(5);

// 2.3 XSS
$pdf->SectionHeader("2.3 Cross-Site Scripting (XSS)");
if(isset($full_res['XSS']['findings']) && !empty($full_res['XSS']['findings'])) {
    $pdf->SetTextColor(255, 100, 0);
    $pdf->Cell(0, 10, "WARNING: XSS Vulnerabilities Detected", 0, 1);
    $pdf->SetTextColor(0);
    foreach($full_res['XSS']['findings'] as $find) {
        $payload = isset($find['payload']) ? $find['payload'] : "N/A";
        $loc = isset($find['location']) ? $find['location'] : "URL";
        $pdf->MultiCell(0, 6, "- Payload: $payload found in $loc", 0, 'L');
    }
} else {
    $pdf->Cell(0, 10, "No XSS vulnerabilities detected.", 0, 1);
}
$pdf->Ln(5);

// 2.4 NIKTO
$pdf->SectionHeader("2.4 Server Misconfigurations (Nikto)");
if(isset($full_res['nikto']['findings']) && !empty($full_res['nikto']['findings'])) {
    foreach($full_res['nikto']['findings'] as $find) {
        $issue = isset($find['issue']) ? $find['issue'] : "Config Issue";
        $pdf->MultiCell(0, 6, "- $issue", 0, 'L');
    }
} else {
    $pdf->Cell(0, 10, "No major misconfigurations found.", 0, 1);
}

// --- RECOMMENDATIONS ---
$pdf->AddPage();
$pdf->ChapterTitle("3. Recommendations & Fixes");
$pdf->SetFont('Arial', '', 11);

$rec_text = "";
if ($risk_score > 0) {
    $rec_text .= "1. Immediate Action Required: Patch critical vulnerabilities found in SQL/XSS sections.\n";
    $rec_text .= "2. Network: Review open ports. Close port 21 (FTP) and 23 (Telnet) if open.\n";
    $rec_text .= "3. Web App: Implement Content Security Policy (CSP) to mitigate XSS.\n";
    $rec_text .= "4. Database: Use Prepared Statements (PDO) for all database queries.\n";
    $rec_text .= "5. Server: Hide server version headers (Security through Obscurity).\n";
} else {
    $rec_text .= "The system appears secure based on current scan parameters. Continue regular audits.";
}
$pdf->MultiCell(0, 8, $rec_text);

// --- RAW OUTPUT OPTION ---
$pdf->AddPage();
$pdf->ChapterTitle("4. Appendix (Raw Data)");
$pdf->SetFont('Courier', '', 8);
$raw_data = json_encode($full_res, JSON_PRETTY_PRINT);
// Limit output to first 2000 chars to prevent PDF memory error
$pdf->MultiCell(0, 5, "Raw JSON Data (Truncated):\n\n" . substr($raw_data, 0, 2000) . "...");

// OUTPUT
$pdf->Output('D', 'AVS_Report_' . $scan_id . '.pdf');
?>